[Setting]
#美版零轨的延迟函数和帧数耦合，高帧数下会和30帧数有所差异，造成脚本演出提前或延后。
#FixSleep开启后会对游戏中的脚本延迟和对话延迟进行补正。
#要求: 游戏帧数稳定在游戏设置中的“帧率限制”，如无法稳定，降低游戏画面设置，开启垂直同步后也需要“刷新率”和“帧率限制”一致。
#设置0关闭，1开启。
FixSleep = 1

[ScenaSleepFactor]
30 = 1.0
60 = 0.95
75 = 0.94
100 = 0.89
120 = 0.895
144 = 0.84

[DialogSleepFactor]
30 = 1.0
60 = 0.975
75 = 0.99
100 = 0.91
120 = 0.97
144 = 0.88